"""
Product-specific field configs for browser demo simulator.
Each product defines inputs, calculated outputs, and a verdict.
"""

PRODUCTS = [
    {
        "slug": "hvac_job_bid",
        "title": "HVAC Job Bid Calculator",
        "tagline": "Know your floor price before you quote",
        "video_file": "stick_HVAC_Job_Bid_Calculator_Quote_Pricing_Decision_Tool_Job_Cost.mp4",
        "inputs": [
            ("Job type", "AC Install + Duct Work"),
            ("Labor hours", "8"),
            ("Tech rate ($/hr)", "$55"),
            ("Materials cost", "$1,840"),
            ("Drive time (hrs)", "1.5"),
            ("Overhead rate", "28%"),
            ("Target margin", "22%"),
        ],
        "outputs": [
            ("Total labor", "$522.50"),
            ("Total job cost", "$2,362.50"),
            ("Floor price", "$3,024.00"),
            ("Recommended quote", "$8,400.00"),
        ],
        "verdict": "Bid it",
        "verdict_type": "success",
        "profit": "+ $2,137.50",
        "persona": "Mike | HVAC Contractor",
    },
    {
        "slug": "crew_profit_tracker",
        "title": "Crew Profit Tracker",
        "tagline": "Which crew is actually making you money?",
        "video_file": "stick_Crew_Profit_Tracker_for_HVAC_Landscaping_Plumbing_Truck_Repl.mp4",
        "inputs": [
            ("Crew name", "Truck 2 — Darnell"),
            ("Jobs this week", "14"),
            ("Revenue collected", "$6,200"),
            ("Labor hours", "52"),
            ("Labor cost", "$1,820"),
            ("Materials & fuel", "$940"),
            ("Overhead share", "18%"),
        ],
        "outputs": [
            ("Total cost", "$3,488.00"),
            ("Gross margin", "$2,712.00"),
            ("Margin %", "43.7%"),
            ("Revenue per hour", "$119.23"),
        ],
        "verdict": "Keep & scale",
        "verdict_type": "success",
        "profit": "+ $2,712.00 / week",
        "persona": "Darnell | Landscaping Crew Owner",
    },
    {
        "slug": "rental_property_dashboard",
        "title": "Rental Property Decision Dashboard",
        "tagline": "Buy, hold, or sell — with real numbers",
        "video_file": "stick_Rental_Property_Decision_Dashboard_AI-Explained_Portfolio_An.mp4",
        "inputs": [
            ("Property address", "412 Maple Ave, Unit 3"),
            ("Purchase price", "$285,000"),
            ("Monthly rent", "$2,100"),
            ("Vacancy rate", "8%"),
            ("Monthly expenses", "$780"),
            ("Mortgage payment", "$1,340"),
            ("Loan amount", "$228,000"),
        ],
        "outputs": [
            ("Net monthly cash flow", "$188.00"),
            ("Cap rate", "5.8%"),
            ("Cash-on-cash return", "7.2%"),
            ("Break-even occupancy", "74%"),
        ],
        "verdict": "Buy it",
        "verdict_type": "success",
        "profit": "+ $2,256 / year cash flow",
        "persona": "Carlos | Landlord, 8 doors",
    },
    {
        "slug": "commercial_real_estate",
        "title": "Commercial RE Deal Analyzer",
        "tagline": "Buy, Negotiate, or Pass — in plain English",
        "video_file": "stick_Real_Estate_Deal_Comparison_Tool_Buy_or_Pass_Decision_Calcul.mp4",
        "inputs": [
            ("Property type", "NNN Retail Strip"),
            ("Purchase price", "$1,850,000"),
            ("Gross rental income", "$168,000"),
            ("Vacancy rate", "6%"),
            ("Operating expenses", "$28,400"),
            ("Loan amount", "$1,480,000"),
            ("Interest rate / amort", "6.8% / 25yr"),
        ],
        "outputs": [
            ("NOI", "$129,208"),
            ("Cap rate", "6.98%"),
            ("DSCR", "1.31x"),
            ("Price per sq ft", "$187"),
        ],
        "verdict": "Bid it",
        "verdict_type": "success",
        "profit": "DSCR clears 1.25x lender threshold",
        "persona": "Jen | Commercial RE Investor",
    },
    {
        "slug": "equipment_replacement",
        "title": "Equipment Replacement Calculator",
        "tagline": "Repair or replace — stop guessing",
        "video_file": "stick_Equipment_Replacement_Decision_Calculator_Repair_vs_Replace_.mp4",
        "inputs": [
            ("Equipment", "2014 Carrier 5-ton unit"),
            ("Repair cost quoted", "$3,200"),
            ("Equipment age (yrs)", "11"),
            ("Replacement cost", "$9,800"),
            ("Remaining useful life", "3 yrs"),
            ("Annual maintenance avg", "$1,100"),
            ("Efficiency loss est.", "22%"),
        ],
        "outputs": [
            ("3-yr repair total", "$6,500"),
            ("3-yr replace total", "$9,800"),
            ("Efficiency savings", "$1,840"),
            ("Net replace advantage", "+ $540"),
        ],
        "verdict": "Replace it",
        "verdict_type": "warning",
        "profit": "Saves $540 over 3 years + no breakdown risk",
        "persona": "Mike | HVAC Contractor",
    },
    {
        "slug": "tenant_retention",
        "title": "Tenant Retention Decision Tool",
        "tagline": "Renew or turn — see the real cost",
        "video_file": "stick_Tenant_Retention_Decision_Tool_Lease_Renewal_vs_Turnover_ROI.mp4",
        "inputs": [
            ("Current rent", "$1,850 / mo"),
            ("Renewal offer", "$1,950 / mo"),
            ("Tenant since", "3 years"),
            ("Turnover cost est.", "$4,200"),
            ("Vacancy weeks if turned", "6 wks"),
            ("New market rent", "$2,050 / mo"),
            ("Rehab needed", "$1,800"),
        ],
        "outputs": [
            ("Renewal annual gain", "$1,200"),
            ("Turnover total cost", "$7,350"),
            ("Break-even months", "6.1 months"),
            ("12-mo net difference", "- $1,950"),
        ],
        "verdict": "Renew the lease",
        "verdict_type": "success",
        "profit": "Renewing saves $1,950 in year one",
        "persona": "Carlos | Landlord, 8 doors",
    },
    {
        "slug": "property_repair_replace",
        "title": "Property Repair vs Replace Tool",
        "tagline": "Maintenance cost ROI before you spend a dollar",
        "video_file": "stick_Property_Repair_vs_Replace_Decision_Tool_Maintenance_Cost_RO.mp4",
        "inputs": [
            ("Component", "Roof — 22yr asphalt shingle"),
            ("Repair quote", "$4,800"),
            ("Replace quote", "$18,500"),
            ("Component age (yrs)", "22"),
            ("Expected life (yrs)", "25"),
            ("Risk of failure (1-10)", "8"),
            ("Rental income at risk", "$2,100/mo"),
        ],
        "outputs": [
            ("Repair ROI", "2.1 yrs to break even"),
            ("Replace ROI", "8.8 yrs"),
            ("Failure cost exposure", "$4,200+"),
            ("Recommended action", "Replace"),
        ],
        "verdict": "Replace now",
        "verdict_type": "warning",
        "profit": "Avoids $4,200 emergency exposure",
        "persona": "Carlos | Landlord, 8 doors",
    },
    {
        "slug": "airbnb_str",
        "title": "Airbnb STR Revenue Tool",
        "tagline": "Which platform actually pays more?",
        "video_file": "stick_Airbnb_STR_Revenue_Decision_Tool_Platform_Profit_Comparison_.mp4",
        "inputs": [
            ("Property", "2BR Condo, Clearwater FL"),
            ("Nightly rate (Airbnb)", "$189"),
            ("Nightly rate (VRBO)", "$199"),
            ("Occupancy (Airbnb)", "74%"),
            ("Occupancy (VRBO)", "68%"),
            ("Platform fee", "3% / 8%"),
            ("Monthly expenses", "$1,240"),
        ],
        "outputs": [
            ("Airbnb monthly net", "$3,186"),
            ("VRBO monthly net", "$2,940"),
            ("Annual difference", "+ $2,952"),
            ("Best platform", "Airbnb"),
        ],
        "verdict": "List on Airbnb",
        "verdict_type": "success",
        "profit": "+ $2,952 / year vs VRBO",
        "persona": "Carlos | STR Investor",
    },
    {
        "slug": "cash_flow_stress_test",
        "title": "Rental Cash Flow Stress Test",
        "tagline": "What happens when vacancy hits 20%?",
        "video_file": "stick_Rental_Property_Cash_Flow_Stress_Test_Refinance_or_Hold_Deci.mp4",
        "inputs": [
            ("Property", "Triplex — Oak St"),
            ("Monthly gross rent", "$4,800"),
            ("Mortgage payment", "$2,640"),
            ("Monthly expenses", "$680"),
            ("Stress vacancy", "25%"),
            ("Rate refinance scenario", "7.2%"),
            ("New loan amount", "$310,000"),
        ],
        "outputs": [
            ("Stressed gross income", "$3,600"),
            ("Stressed net cash flow", "+ $280"),
            ("Refi payment", "$2,105"),
            ("Refi cash flow", "+ $815"),
        ],
        "verdict": "Hold — refinance",
        "verdict_type": "success",
        "profit": "Survives 25% vacancy + refi adds $535/mo",
        "persona": "Carlos | Landlord, 8 doors",
    },
    {
        "slug": "recurring_customer_profitability",
        "title": "Recurring Customer Profitability Tracker",
        "tagline": "Which clients are actually worth keeping?",
        "video_file": "stick_Recurring_Customer_Profitability_Tracker_Which_Clients_Make_.mp4",
        "inputs": [
            ("Client name", "Harborview HOA"),
            ("Monthly revenue", "$2,400"),
            ("Hours per month", "18"),
            ("Labor cost", "$630"),
            ("Materials & supplies", "$280"),
            ("Admin time (hrs)", "2"),
            ("Overhead allocation", "15%"),
        ],
        "outputs": [
            ("Monthly profit", "$1,130"),
            ("Profit margin", "47.1%"),
            ("Effective hourly rate", "$62.78"),
            ("Annual value", "$13,560"),
        ],
        "verdict": "Priority client",
        "verdict_type": "success",
        "profit": "$13,560 / year — protect this contract",
        "persona": "Tony | Plumbing Business Owner",
    },
    {
        "slug": "seasonal_cash_flow",
        "title": "Seasonal Business Cash Flow Planner",
        "tagline": "Plan your slow months before they hit",
        "video_file": "stick_Seasonal_Business_Cash_Flow_Planner_Staffing_and_Layoff_Timi.mp4",
        "inputs": [
            ("Business type", "Landscaping / Snow removal"),
            ("Peak monthly revenue", "$48,000"),
            ("Off-season revenue", "$8,200"),
            ("Fixed monthly costs", "$14,400"),
            ("Variable cost rate", "38%"),
            ("Cash reserve current", "$22,000"),
            ("Off-season months", "3"),
        ],
        "outputs": [
            ("Off-season monthly burn", "$17,716"),
            ("Reserve needed", "$31,148"),
            ("Current gap", "- $9,148"),
            ("Layoff saves / month", "$4,800"),
        ],
        "verdict": "Lay off 2 — rebuild reserve",
        "verdict_type": "warning",
        "profit": "Saves $9,148 reserve gap with temp layoff",
        "persona": "Darnell | Landscaping Crew Owner",
    },
    {
        "slug": "quote_to_close",
        "title": "Quote to Close Tracker",
        "tagline": "Which lead source actually converts?",
        "video_file": "stick_Quote_to_Close_Tracker_Win_Rate_by_Lead_Source_Decision_Tool.mp4",
        "inputs": [
            ("Lead source", "Google LSA"),
            ("Quotes sent (mo)", "28"),
            ("Jobs won", "19"),
            ("Avg job value", "$1,840"),
            ("Cost per lead", "$68"),
            ("Total lead spend", "$1,904"),
            ("Close rate", "67.9%"),
        ],
        "outputs": [
            ("Monthly revenue", "$34,960"),
            ("Cost per closed job", "$100.21"),
            ("Revenue per lead $", "$18.36"),
            ("ROI on ad spend", "18.4x"),
        ],
        "verdict": "Scale this channel",
        "verdict_type": "success",
        "profit": "18.4x ROI — double the LSA budget",
        "persona": "Tony | Plumbing Business Owner",
    },
    {
        "slug": "service_business_expansion",
        "title": "Service Business Expansion Calculator",
        "tagline": "When to hire a crew or open a new market",
        "video_file": "stick_Service_Business_Expansion_Calculator_When_to_Hire_a_Crew_or.mp4",
        "inputs": [
            ("Current revenue / mo", "$38,000"),
            ("Current capacity used", "94%"),
            ("New hire total cost/mo", "$5,800"),
            ("New market setup cost", "$12,400"),
            ("Revenue uplift est.", "$14,000/mo"),
            ("Ramp-up period", "3 months"),
            ("Risk tolerance (1-5)", "3"),
        ],
        "outputs": [
            ("Break-even month", "Month 4"),
            ("12-mo net gain", "+ $84,600"),
            ("Capacity after hire", "68%"),
            ("Payback period", "3.7 months"),
        ],
        "verdict": "Hire now",
        "verdict_type": "success",
        "profit": "+ $84,600 by month 12",
        "persona": "Tony | Plumbing Business Owner",
    },
    {
        "slug": "technician_profitability",
        "title": "Technician Profitability Scorecard",
        "tagline": "Keep, coach, or cut — with real numbers",
        "video_file": "stick_Technician_Profitability_Scorecard_Keep_Coach_or_Cut_Decisio.mp4",
        "inputs": [
            ("Technician name", "Jesse R."),
            ("Revenue generated", "$18,400/mo"),
            ("Labor cost (w/ burden)", "$4,960"),
            ("Callbacks / rework", "3"),
            ("Callback cost avg", "$320"),
            ("Upsell rate", "14%"),
            ("Customer rating avg", "4.2 / 5"),
        ],
        "outputs": [
            ("Gross profit", "$12,480"),
            ("Profit margin", "67.8%"),
            ("Rework cost drag", "$960/mo"),
            ("Adjusted margin", "62.6%"),
        ],
        "verdict": "Coach — reduce callbacks",
        "verdict_type": "warning",
        "profit": "Fix callbacks = + $960/mo recovered",
        "persona": "Mike | HVAC Contractor",
    },
    {
        "slug": "materials_markup",
        "title": "Materials Markup Profit Leak Calculator",
        "tagline": "Where are you losing money on parts?",
        "video_file": "stick_Materials_Markup_Profit_Leak_Calculator_Where_Are_You_Losing.mp4",
        "inputs": [
            ("Material category", "Refrigerant — R-410A"),
            ("Your cost per lb", "$18.40"),
            ("Current markup", "35%"),
            ("Charged to customer", "$24.84"),
            ("Industry markup avg", "60%"),
            ("Monthly volume (lbs)", "220"),
            ("Competitor price check", "$29.44/lb"),
        ],
        "outputs": [
            ("Current monthly margin", "$1,421"),
            ("At 60% markup", "$2,016"),
            ("Monthly profit leak", "- $595"),
            ("Annual leak", "- $7,140"),
        ],
        "verdict": "Raise markup to 55%",
        "verdict_type": "warning",
        "profit": "Recover up to $7,140 / year",
        "persona": "Mike | HVAC Contractor",
    },
    {
        "slug": "marketing_roi",
        "title": "Marketing ROI Calculator",
        "tagline": "Which ads are actually paying off?",
        "video_file": "stick_Marketing_ROI_Cost_Per_Customer_Calculator_Which_Ads_Actuall.mp4",
        "inputs": [
            ("Channel", "Facebook / Instagram Ads"),
            ("Monthly ad spend", "$1,200"),
            ("Leads generated", "34"),
            ("Close rate", "41%"),
            ("Avg job value", "$1,640"),
            ("Customer lifetime", "2.4 jobs"),
            ("Churn rate", "28%"),
        ],
        "outputs": [
            ("Closed jobs / mo", "14"),
            ("Revenue attributed", "$22,960"),
            ("Cost per customer", "$85.71"),
            ("LTV per customer", "$3,936"),
        ],
        "verdict": "Scale — strong ROI",
        "verdict_type": "success",
        "profit": "19.1x return on ad spend",
        "persona": "Darnell | Landscaping Crew Owner",
    },
    {
        "slug": "service_area_density",
        "title": "Service Area Density Calculator",
        "tagline": "Accept or decline — is the route worth it?",
        "video_file": "stick_Service_Area_Density_Route_Profit_Calculator_Accept_or_Decli.mp4",
        "inputs": [
            ("Job location", "Pinellas Park — 38 mi"),
            ("Drive time (one way)", "52 min"),
            ("Job revenue", "$1,280"),
            ("Tech hourly cost", "$38"),
            ("Fuel cost est.", "$24"),
            ("Nearby jobs possible", "0"),
            ("Min acceptable margin", "40%"),
        ],
        "outputs": [
            ("Drive cost total", "$89.07"),
            ("Effective job revenue", "$1,190.93"),
            ("True margin", "38.1%"),
            ("Break even distance", "31 mi"),
        ],
        "verdict": "Decline or reprice",
        "verdict_type": "danger",
        "profit": "Below 40% margin — add $28 fuel surcharge",
        "persona": "Tony | Plumbing Business Owner",
    },
    {
        "slug": "price_increase",
        "title": "Price Increase Decision Calculator",
        "tagline": "How much can you raise rates without losing jobs?",
        "video_file": "stick_Price_Increase_Decision_Calculator_How_Much_Can_I_Raise_Rate.mp4",
        "inputs": [
            ("Current hourly rate", "$95"),
            ("Proposed rate", "$110"),
            ("Monthly jobs", "62"),
            ("Estimated churn at +15%", "8%"),
            ("Cost of acquiring new job", "$120"),
            ("Current close rate", "58%"),
            ("Break-even churn", "12%"),
        ],
        "outputs": [
            ("Jobs lost est.", "5"),
            ("Revenue change", "+ $4,865"),
            ("Churn cost", "- $600"),
            ("Net monthly gain", "+ $4,265"),
        ],
        "verdict": "Raise to $110",
        "verdict_type": "success",
        "profit": "+ $4,265 / month at new rate",
        "persona": "Mike | HVAC Contractor",
    },
    {
        "slug": "callback_rework",
        "title": "Callback Rework Cost Calculator",
        "tagline": "What are free redo jobs really costing you?",
        "video_file": "stick_Callback_Rework_Cost_Calculator_What_Are_Free_Redo_Jobs_Real.mp4",
        "inputs": [
            ("Callbacks this month", "7"),
            ("Avg callback drive time", "45 min"),
            ("Avg rework time (hrs)", "2.1"),
            ("Tech hourly burden", "$52"),
            ("Parts used on rework", "$185"),
            ("Jobs displaced", "4"),
            ("Avg job value", "$1,420"),
        ],
        "outputs": [
            ("Direct rework cost", "$2,054"),
            ("Opportunity cost", "$5,680"),
            ("Total monthly drag", "$7,734"),
            ("Annual exposure", "$92,808"),
        ],
        "verdict": "Critical — fix root cause",
        "verdict_type": "danger",
        "profit": "$92,808 / year hidden cost",
        "persona": "Tony | Plumbing Business Owner",
    },
    {
        "slug": "real_estate_deal_comparison",
        "title": "Real Estate Deal Comparison Tool",
        "tagline": "Compare 5 deals side by side — Buy or Pass",
        "video_file": "stick_Real_Estate_Deal_Comparison_Tool_Buy_or_Pass_Decision_Calcul.mp4",
        "inputs": [
            ("Deal A — address", "812 Citrus Ave"),
            ("Purchase price", "$324,000"),
            ("Monthly rent est.", "$2,400"),
            ("Deal B — address", "44 Harbor Blvd"),
            ("Purchase price", "$289,000"),
            ("Monthly rent est.", "$2,050"),
            ("Target cash-on-cash", "7%"),
        ],
        "outputs": [
            ("Deal A — CoC return", "8.1%"),
            ("Deal B — CoC return", "5.9%"),
            ("Deal A — cap rate", "6.4%"),
            ("Deal B — cap rate", "5.2%"),
        ],
        "verdict": "Buy Deal A — pass Deal B",
        "verdict_type": "success",
        "profit": "Deal A clears target by 1.1%",
        "persona": "Jen | RE Investor",
    },
]

# Map slug → config for fast lookup
PRODUCT_MAP = {p["slug"]: p for p in PRODUCTS}
